### ISSUE TITLE
Kotest Gradle plugin is missing in snapshot publications

### ISSUE THREAD

**Issue by OliverO2** [kotest/kotest#4012]
The `io.kotest.multiplatform` Gradle plugin (`io.kotest:kotest-framework-multiplatform-plugin-gradle`) is not published to the [snapshot repo](https://s01.oss.sonatype.org/content/repositories/snapshots/io/kotest/). This complicates configuring Kotest dependencies (separate version for plugin and libraries required) and blocks using snapshots which require an updated plugin.

**Comment by OliverO2** [comment]
Maybe adding the last line of this to `.github/workflows/master.yml` would suffice?
```
jobs:
   linux:
      strategy:
         matrix:
            target:
               - :kotest-framework:kotest-framework-multiplatform-plugin-gradle:publish
```
