### ISSUE TITLE
IncompatibleClassChangeError with Kotlin 2.0.20-Beta2 for native (iOS) targets

### ISSUE THREAD

**Issue by JesusMcCloud** [kotest/kotest#4177]
**Which version of Kotest are you using**
Kotest 5.9.1

Hi!

We ran into an issue testing our KMP codebase against Kotlin 2.0.20-Beta2 (Beta1 works, 2.0.10-RC also works).
Kotest fails to start the iOS tests due to an IncompatibleClassChangeError. [Here's](https://github.com/a-sit-plus/kmm-vc-library/actions/runs/9986168884/job/27598202067#step:5:440) the output of out CI pipeline triggering it.

**Comment by OliverO2** [comment]
Thanks! Looks like a [change in the Kotlin compiler](https://github.com/JetBrains/kotlin/commit/7f6562285b6b228e435550e1a0a5a12fbab9a6cb) that requires updating the Kotest compiler plugin.

```
e: java.lang.IncompatibleClassChangeError: Found class org.jetbrains.kotlin.ir.declarations.IrFactory, but interface was expected
	at io.kotest.framework.multiplatform.embeddablecompiler.NativeTransformer.generateLauncher(NativeTransformer.kt:46)
	at io.kotest.framework.multiplatform.embeddablecompiler.Transformer.visitModuleFragment(Transformer.kt:65)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitModuleFragment(IrElementTransformerVoid.kt:113)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitModuleFragment(IrElementTransformerVoid.kt:19)
	at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.accept(IrModuleFragment.kt:33)
	at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.transform(IrModuleFragment.kt:36)
	at io.kotest.framework.multiplatform.embeddablecompiler.SpecIrGenerationExtension.generate(SpecIrGenerationExtension.kt:23)
	at org.jetbrains.kotlin.fir.pipeline.ConvertToIrKt.applyIrGenerationExtensions(convertToIr.kt:437)
	at org.jetbrains.kotlin.fir.pipeline.Fir2IrPipeline.runActualizationPipeline(convertToIr.kt:246)
	at org.jetbrains.kotlin.fir.pipeline.Fir2IrPipeline.convertToIrAndActualize(convertToIr.kt:130)
	at org.jetbrains.kotlin.fir.pipeline.ConvertToIrKt.convertToIrAndActualize(convertToIr.kt:99)
	at org.jetbrains.kotlin.fir.pipeline.ConvertToIrKt.convertToIrAndActualize$default(convertToIr.kt:72)
	at org.jetbrains.kotlin.backend.konan.Fir2IrKt.fir2Ir(Fir2Ir.kt:99)
```

**Comment by sksamuel** [comment]
The latest snapshot might have this fixed @JesusMcCloud

**Comment by JesusMcCloud** [comment]
it is indeed fixed with latest 6.0.0 SNAPSHOT. Thank you very much!

Still keeping this one open until 6.0.0 is released. Feel free to close at your own discretion.

**Comment by YSakhno** [comment]
Are there plans to backport the fix to **5.9.x**?

**Comment by JesusMcCloud** [comment]
> Are there plans to backport the fix to **5.9.x**?

We've just switched to using 6.0.0-SNAPSHOT. Works like a charm even on complex KMP projects!

**Comment by CLOVIS-AI** [comment]
Could it be possible to publish a version with this fix? Even if it's a `6.0.0-alpha.1` or similar, it doesn't have to be stable, I just can't depend on `-SNAPSHOT` versions because they are mutable.

**Comment by alyssa-nash** [comment]
I am also going to lend my voice to asking for a release for the fix for this breaking bug. Especially since kotest does not work with the latest stable version of Kotlin without it. I cannot use a constantly changing snapshot library to test production code.

**Comment by JesusMcCloud** [comment]
In the meantime, we're using snapshot version 6.0.0-20240905.065253-61 as a test dependency. This version works for iOS, JVM, Android and is not mutable.

**Comment by alyssa-nash** [comment]
I apologize if I am missing something, but I am getting `Failed to resolve: io.kotest:kotest-property:6.0.0-20240905.065253-61` errors. When I look on s01.oss.sonatype.org I see the usual structure is 6.0.0.(some number)-morenumbers. The highest snapshot in the directory is 6.0.0-1564 which still provides the original error since it predates the fix. Is there a better way to look through snapshots?

**Comment by JesusMcCloud** [comment]
@alyssa-nash maybe you are not using a recent enough gradle version? if you look into the repo, [it is there](https://s01.oss.sonatype.org/content/repositories/snapshots/io/kotest/kotest-property/6.0.0-SNAPSHOT/).

**Comment by OliverO2** [comment]
Gradle needs a special setup to access snapshot artifacts.

This is what I'm using to access the snapshots repo for the Kotest Gradle plugin:

In `settings.gradle.kts`:

```kotlin
@Suppress("UnstableApiUsage")
dependencyResolutionManagement {
    pluginManagement {
        repositories {
            specialRepositories()
            gradlePluginPortal()
        }
    }
    repositories {
        mavenCentral()
        specialRepositories()
    }
}

fun RepositoryHandler.specialRepositories() {
    maven("https://s01.oss.sonatype.org/content/repositories/snapshots/") {
        name = "MavenCentralSnapshots"
        mavenContent { snapshotsOnly() }
    }
}
```

In `gradle/libs.versions.toml`:

```toml
[versions]

# https://github.com/kotest/kotest/releases
io-kotest = "5.9.1"
io-kotest-gradle-plugin = "6.0.0-20240905.065253-61"

# https://github.com/JetBrains/kotlin/releases
org-jetbrains-kotlin = "2.0.20"

[libraries]

io-kotest-kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "io-kotest" }
io-kotest-kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "io-kotest" }

[plugins]

io-kotest-multiplatform = { id = "io.kotest.multiplatform", version.ref = "io-kotest-gradle-plugin" }
org-jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "org-jetbrains-kotlin" }
```

In `build.gradle.kts`:

```kotlin
plugins {
    alias(libs.plugins.org.jetbrains.kotlin.multiplatform)
    alias(libs.plugins.io.kotest.multiplatform)
}

kotlin {
    linuxX64 {
        binaries.executable()
    }

    sourceSets {
        val commonTest by getting {
            dependencies {
                implementation(libs.io.kotest.kotest.framework.engine)
                implementation(libs.io.kotest.kotest.assertions.core)
            }
        }
    }
}
```

Does that help?
