### ISSUE TITLE
Starting to see InterruptedExceptions with kotlintest 3.2.0

### ISSUE THREAD

**Issue by sschuberth** [kotest/kotest#588]
While running tests on the [PR that migrates our app to kotlintest 3.2.0](https://github.com/heremaps/oss-review-toolkit/pull/1195) I start to see `InterruptedExceptions` where previously (with kotlintest 3.1.11) everything was fine. See e.g.

https://travis-ci.com/heremaps/oss-review-toolkit/builds/97502719#L1263
https://ci.appveyor.com/project/heremaps/oss-review-toolkit/builds/21656801#L3532

I'm wondering whether that's related to the [fix for test timeouts](https://github.com/kotlintest/kotlintest/issues/476) that was merged as part of #518.

**Comment by LeoColman** [comment]
Looking into it now.

**Comment by LeoColman** [comment]
Ok, I'm not able to run the tests that failed. any tip on how to reproduce that issue?

**Comment by sschuberth** [comment]
> Ok, I'm not able to run the tests that failed.

What exactly is the problem?

> any tip on how to reproduce that issue?

You could try cloning the [oss-review-toolkit](https://github.com/heremaps/oss-review-toolkit) repo, checking out the [kotlintest-3.2.0](https://github.com/heremaps/oss-review-toolkit/tree/kotlintest-3.2.0) branch, ensuring you have [sbt](https://www.scala-sbt.org/) installed and in your `PATH`, and then running

    ./gradlew :analyzer:funTest --tests com.here.ort.analyzer.SbtTest

**Comment by LeoColman** [comment]
Ok, let me try to run it that way.

**Comment by LeoColman** [comment]
I'm not getting an assertion error.
```
org.opentest4j.AssertionFailedError: expected: "---
    repository:
      vcs:
        type: "Git"
        url: "https://github.com/soc/directories-jvm"
        revision: "d302b1e93963c81ed511e072a52e95251b5d078b"
        path: ""
      vcs_processed:
        type: "git"
        url: "https://github.com/soc/directories-jvm.git"
        revision: "d302b1e93963c81ed511e072a52e95251b5d078b"
        path: ""
      config: {}
    analyzer:
      environment:
        os: "Linux"
        tool_versions: {}
      config:
        ignore_tool_versions: false
        allow_dynamic_versions: false
      result:
        projects:
        - id: "SBT:io.github.soc:directories:10"
          definition_file_path: "target/directories-10.pom"
          declared_licenses:
          - "Mozilla Public License 2.0"
          vcs:
            type: "git"
            url: "git@github.com:soc/directories-jvm.git"
            revision: ""
            path: ""
          vcs_processed:
            type: "git"
            url: "https://github.com/soc/directories-jvm.git"
            revision: "d302b1e93963c81ed511e072a52e95251b5d078b"
            path: ""
          homepage_url: "https://github.com/soc/directories-jvm"
          scopes:
          - name: "test"
            dependencies:
            - id: "Maven:com.novocode:junit-interface:0.11"
              dependencies:
              - id: "Maven:org.scala-sbt:test-interface:1.0"
            - id: "Maven:junit:junit:4.12"
              dependencies:
              - id: "Maven:org.hamcrest:hamcrest-core:1.3"
        packages:
        - package:
            id: "Maven:com.novocode:junit-interface:0.11"
            declared_licenses:
            - "Two-clause BSD-style license"
            description: "An implementation of sbt's test interface for JUnit 4"
            homepage_url: "http://github.com/sbt/junit-interface/"
            binary_artifact:
              url: "https://repo.maven.apache.org/maven2/com/novocode/junit-interface/0.11/junit-interface-0.11.jar"
              hash: "38bb853c93abfbe14a0514016f0f70dd73422d9f"
              hash_algorithm: "SHA-1"
            source_artifact:
              url: "https://repo.maven.apache.org/maven2/com/novocode/junit-interface/0.11/junit-interface-0.11-sources.jar"
              hash: "c7c1394bbc5718aa256557544d891b3842825a8d"
              hash_algorithm: "SHA-1"
            vcs:
              type: "git"
              url: "git@github.com:sbt/junit-interface.git"
              revision: ""
              path: ""
            vcs_processed:
              type: "git"
              url: "ssh://git@github.com/sbt/junit-interface.git"
              revision: ""
              path: ""
          curations: []
        - package:
            id: "Maven:junit:junit:4.12"
            declared_licenses:
            - "Eclipse Public License 1.0"
            description: "JUnit is a unit testing framework for Java, created by Erich\
              \ Gamma and Kent Beck."
            homepage_url: "http://junit.org"
            binary_artifact:
              url: "https://repo.maven.apache.org/maven2/junit/junit/4.12/junit-4.12.jar"
              hash: "2973d150c0dc1fefe998f834810d68f278ea58ec"
              hash_algorithm: "SHA-1"
            source_artifact:
              url: "https://repo.maven.apache.org/maven2/junit/junit/4.12/junit-4.12-sources.jar"
              hash: "a6c32b40bf3d76eca54e3c601e5d1470c86fcdfa"
              hash_algorithm: "SHA-1"
            vcs:
              type: "git"
              url: "git://github.com/junit-team/junit.git"
              revision: "r4.12"
              path: ""
            vcs_processed:
              type: "git"
              url: "https://github.com/junit-team/junit.git"
              revision: "r4.12"
              path: ""
          curations: []
        - package:
            id: "Maven:org.hamcrest:hamcrest-core:1.3"
            declared_licenses:
            - "New BSD License"
            description: "This is the core API of hamcrest matcher framework to be used\
              \ by third-party framework providers. This includes the a foundation set\
              \ of matcher implementations for common operations."
            homepage_url: "https://github.com/hamcrest/JavaHamcrest/hamcrest-core"
            binary_artifact:
              url: "https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar"
              hash: "42a25dc3219429f0e5d060061f71acb49bf010a0"
              hash_algorithm: "SHA-1"
            source_artifact:
              url: "https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3-sources.jar"
              hash: "1dc37250fbc78e23a65a67fbbaf71d2e9cbc3c0b"
              hash_algorithm: "SHA-1"
            vcs:
              type: "git"
              url: "git@github.com:hamcrest/JavaHamcrest.git"
              revision: ""
              path: ""
            vcs_processed:
              type: "git"
              url: "ssh://git@github.com/hamcrest/JavaHamcrest.git"
              revision: ""
              path: ""
          curations: []
        - package:
            id: "Maven:org.scala-sbt:test-interface:1.0"
            declared_licenses:
            - "BSD"
            description: "Uniform test interface to Scala/Java test frameworks (specs,\
              \ ScalaCheck, ScalaTest, JUnit and other)"
            homepage_url: "http://www.scala-sbt.org"
            binary_artifact:
              url: "https://repo.maven.apache.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar"
              hash: "0a3f14d010c4cb32071f863d97291df31603b521"
              hash_algorithm: "SHA-1"
            source_artifact:
              url: "https://repo.maven.apache.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0-sources.jar"
              hash: "d44b23e9e3419ad0e00b91bba764a48d43075000"
              hash_algorithm: "SHA-1"
            vcs:
              type: ""
              url: ""
              revision: ""
              path: ""
            vcs_processed:
              type: ""
              url: ""
              revision: ""
              path: ""
          curations: []
        has_errors: false
    scanner: null
    evaluator: null
    " but was: "---
    repository:
      vcs:
        type: "Git"
        url: "https://github.com/heremaps/oss-review-toolkit"
        revision: "5a18ff534a96828a2d58379d0b2af4fc659c307e"
        path: "analyzer/src/funTest/assets/projects/external/directories"
      vcs_processed:
        type: "git"
        url: "https://github.com/heremaps/oss-review-toolkit.git"
        revision: "5a18ff534a96828a2d58379d0b2af4fc659c307e"
        path: "analyzer/src/funTest/assets/projects/external/directories"
      config: {}
    analyzer:
      environment:
        os: "Linux"
        tool_versions: {}
      config:
        ignore_tool_versions: false
        allow_dynamic_versions: false
      result:
        projects:
        - id: "Unmanaged::directories:"
          definition_file_path: ""
          declared_licenses: []
          vcs:
            type: ""
            url: ""
            revision: ""
            path: ""
          vcs_processed:
            type: "Git"
            url: "https://github.com/heremaps/oss-review-toolkit"
            revision: "5a18ff534a96828a2d58379d0b2af4fc659c307e"
            path: "analyzer/src/funTest/assets/projects/external/directories"
          homepage_url: ""
          scopes: []
        packages: []
        has_errors: false
    scanner: null
    evaluator: null
    "
```
